In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
df = pd.read_csv('/Users/fahad/GP-ML/Data/loan-train.csv')

In [3]:
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [5]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [6]:
df.shape

(614, 13)

In [11]:
df = df.fillna(df.mean(numeric_only=True))

In [12]:
df.Gender = df.Gender.replace({"Male": 1, "Female" : 0})
df.Married = df.Married.replace({"Yes": 1, "No" : 0})
df.Loan_Status = df.Loan_Status.replace({"Y": 1, "N" : 0})
df.Self_Employed = df.Self_Employed.replace({"Yes": 1, "No" : 0})

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             614 non-null    float64
 2   Married            614 non-null    float64
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      614 non-null    float64
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    int64  
dtypes: float64(7), int64(2), object(4)
memory usage: 62.5+ KB


In [14]:
df['Gender'] = df['Gender'].astype(int)
df['Married'] = df['Married'].astype(int)
df['Self_Employed'] = df['Self_Employed'].astype(int)
df['Self_Employed'] = df['Self_Employed'].astype(int)
df['ApplicantIncome'] = df['ApplicantIncome'].astype(float)
df['Credit_History'] = df['Credit_History'].astype(int)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             614 non-null    int32  
 2   Married            614 non-null    int32  
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      614 non-null    int32  
 6   ApplicantIncome    614 non-null    float64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    int32  
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    int64  
dtypes: float64(4), int32(4), int64(1), object(4)
memory usage: 52.9+ KB


In [16]:
features  = df.drop(['Loan_ID','Dependents','Property_Area','Education','Loan_Amount_Term','Loan_Status'], axis=1).values
features 

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 1.46412162e+02, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        1.50800000e+03, 1.28000000e+02, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 6.60000000e+01, 1.00000000e+00],
       ...,
       [1.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        2.40000000e+02, 2.53000000e+02, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 1.87000000e+02, 1.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 1.33000000e+02, 0.00000000e+00]])

In [17]:
target = df['Loan_Amount_Term'].values
target.reshape(-1,1)

array([[360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [120.],
       [360.],
       [240.],
       [360.],
       [360.],
       [342.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [342.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [342.],
       [342.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [360.],
       [180.],
       [360.],
       [360.],
       [360.],
       [18

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test = train_test_split(features,target,test_size=0.3,random_state=0)

In [20]:
x_train.shape,y_train.shape

((429, 7), (429,))

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
scaler = StandardScaler()
x_train[3:5] = scaler.fit_transform(x_train[3:5])
x_test[3:5] = scaler.transform(x_test[3:5])

In [23]:
x_train,x_test

(array([[1.000e+00, 0.000e+00, 0.000e+00, ..., 4.167e+03, 3.080e+02,
         1.000e+00],
        [1.000e+00, 1.000e+00, 0.000e+00, ..., 3.300e+03, 1.420e+02,
         1.000e+00],
        [1.000e+00, 1.000e+00, 0.000e+00, ..., 2.167e+03, 1.150e+02,
         1.000e+00],
        ...,
        [1.000e+00, 1.000e+00, 0.000e+00, ..., 3.167e+03, 2.000e+02,
         1.000e+00],
        [1.000e+00, 1.000e+00, 0.000e+00, ..., 0.000e+00, 1.600e+02,
         1.000e+00],
        [0.000e+00, 1.000e+00, 0.000e+00, ..., 2.306e+03, 1.820e+02,
         1.000e+00]]),
 array([[1.000e+00, 0.000e+00, 1.000e+00, ..., 0.000e+00, 8.400e+01,
         1.000e+00],
        [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 1.120e+02,
         1.000e+00],
        [1.000e+00, 1.000e+00, 0.000e+00, ..., 3.906e+03, 3.240e+02,
         1.000e+00],
        ...,
        [0.000e+00, 1.000e+00, 0.000e+00, ..., 0.000e+00, 3.600e+01,
         1.000e+00],
        [1.000e+00, 1.000e+00, 0.000e+00, ..., 0.000e+00, 1.700e+02,
   

In [24]:
from sklearn.ensemble import RandomForestRegressor

In [25]:
ml_model = RandomForestRegressor()

In [26]:
ml_model.fit(x_train, y_train)

RandomForestRegressor()

In [27]:
y_pred = ml_model.predict(x_test)
y_pred

array([258.9 , 343.8 , 339.24, 314.4 , 313.8 , 337.68, 367.2 , 359.4 ,
       360.  , 371.22, 351.84, 361.2 , 357.36, 354.  , 327.96, 319.02,
       352.62, 388.44, 355.44, 361.2 , 308.34, 349.2 , 310.26, 326.22,
       346.8 , 352.2 , 347.04, 331.2 , 358.2 , 366.66, 347.4 , 320.22,
       347.52, 331.56, 300.24, 352.44, 324.24, 354.24, 325.2 , 291.  ,
       234.72, 366.84, 283.8 , 357.78, 308.64, 329.82, 331.2 , 342.  ,
       352.8 , 348.06, 260.22, 356.82, 340.56, 361.8 , 356.22, 352.2 ,
       356.28, 358.2 , 354.96, 322.2 , 320.28, 349.2 , 356.22, 317.82,
       343.2 , 351.6 , 343.38, 372.3 , 352.8 , 325.14, 299.46, 345.6 ,
       356.58, 352.8 , 350.64, 358.2 , 270.84, 352.02, 291.84, 345.78,
       352.86, 343.2 , 346.74, 314.1 , 337.32, 310.56, 356.22, 317.4 ,
       354.6 , 360.  , 371.4 , 289.26, 343.2 , 340.32, 348.  , 337.56,
       352.2 , 355.98, 337.38, 271.8 , 347.4 , 353.46, 331.02, 321.42,
       356.4 , 360.  , 341.22, 349.56, 374.4 , 326.04, 349.8 , 347.04,
      

In [28]:
from sklearn.metrics import accuracy_score
score = ml_model.score(x_train, y_train)
print('accuracy_score overall :', score)
print('accuracy_score percent :', round(score*100,2))

accuracy_score overall : 0.8495905959575587
accuracy_score percent : 84.96


In [29]:
x_test

array([[1.000e+00, 0.000e+00, 1.000e+00, ..., 0.000e+00, 8.400e+01,
        1.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 1.120e+02,
        1.000e+00],
       [1.000e+00, 1.000e+00, 0.000e+00, ..., 3.906e+03, 3.240e+02,
        1.000e+00],
       ...,
       [0.000e+00, 1.000e+00, 0.000e+00, ..., 0.000e+00, 3.600e+01,
        1.000e+00],
       [1.000e+00, 1.000e+00, 0.000e+00, ..., 0.000e+00, 1.700e+02,
        1.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 1.020e+02,
        1.000e+00]])

In [30]:
ml_model.predict([[0,0,0,6000,0.0,133,1]])

array([374.4])

In [31]:
import pickle as pkl

In [32]:
filename = 'loan_amount_term_model.pkl'
pkl.dump(ml_model, open(filename, 'wb'))